# charts/traefik/values.yaml
deployment:
  kind: Deployment
  replicas: 1

service:
  enabled: true
  type: NodePort  # This allows you to access Traefik from your browser
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

ports:
  web:
    port: 8000
    nodePort: 30080
    exposedPort: 80
  websecure:
    port: 8443
    nodePort: 30443
    exposedPort: 443
  traefik:
    port: 9000
    nodePort: 30000
    expose:
      default: true
    
ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
