apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dbproject
  labels:
    app: frontend 

spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend

  template: 
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: joshhy0ra/databaseproject:frontend-f01eccc
          ports:
            - containerPort: 80

