apiVersion: v1
kind: Service
metadata:
  name: frontend 
  namespace: dbproject

spec:
  selector:
    app: frontend

  ports: 
    - port: 80 # The external port for your service
      targetPort: 80 # The port on which your app is running in the container
  
  type: ClusterIP # if you have a LoadBalancer, it goes here.
