apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dbproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: flask
          image: joshhy0ra/databaseproject:backend-92a97b3
          ports:
            - containerPort: 5000
          env:
          - name: DATABASE_URL 
            valueFrom: 
              secretKeyRef:
                name: backend-secrets
                key: DATABASE_URL
