apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  project: default
  source:
    repoURL: https://github.com/Joshy0u/k8s-infrastructure
    path: charts/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: dbproject 
  syncPolicy:
    automated:
      prune: false 
      selfHeal: false

